version: '3.7'

services:
  currency-exchange-service:
    image: muhammedshaheer/currency-exchange-service
    mem_limit: 700m
    ports:
      - 8000:8000
    networks:
      - currency-network

networks:
  currency-network: